export const LIMIT_GARAGE_DEFAULT = 7;
export const LIMIT_WINNERS_DEFAULT = 10;

export const GARAGE_API = 'http://127.0.0.1:3000/garage';
export const ENGINE_API = 'http://127.0.0.1:3000/engine';
export const WINNERS_API = 'http://127.0.0.1:3000/winners';

export const CAR_COLORS = [
    '#36454F',
    '#023020',
    '#301934',
    '#343434',
    '#1B1212',
    '#191970',
    '#89CFF0',
    '#7393B3',
    '#088F8F',
    '#00A36C',
    '#5D3FD3',
    '#4682B4',
    '#CD7F32',
    '#A52A2A',
    '#DAA06D',
    '#E97451',
    '#6E260E',
    '#C19A6B',
    '#7B3F00',
    '#B87333',
    '#966919',
    '#808000',
    '#913831',
    '#722F37',
    '#454B1B',
    '#E4D00A',
    '#4F7942',
    '#2AAA8A',
    '#0BDA51',
    '#C9CC3F',
    '#93C572',
    '#CC5500',
    '#F88379',
    '#C04000',
    '#FA5F55',
    '#FFAA33',
    '#DE3163',
    '#DC143C',
    '#FF69B4',
    '#770737',
    '#673147',
    '#C21E56',
    '#E0BFB8',
    '#483248',
    '#51414F',
    '#FF0000',
    '#A52A2A',
    '#E34234',
    '#A42A04',
    '#FFFF8F',
    '#FDDA0D',
    '#DAA520',
    '#FCF55F',
    '#F4BB44',
    '#FAD5A5',
    '#8B8000',
];

export const CAR_NAMES = [
    'Acura',
    'Alfa Romeo',
    'Alpine',
    'Apollo',
    'Apple',
    'Aston Martin',
    'Audi',
    'Bentley',
    'BMW',
    'Bollinger',
    'Brilliance',
    'Bugatti',
    'Buick',
    'BYD',
    'Cadillac',
    'Chana',
    'Chery',
    'Chevrolet',
    'Chrysler',
    'Citroen',
    'Continental',
    'CUPRA',
    'Dacia',
    'Daewoo',
    'Daihatsu',
    'Datsun',
    'Detroit Electric',
    'Dodge',
    'DS Automobiles',
    'FAW',
    'Ferrari',
    'Fiat',
    'Fisker',
    'Ford',
    'Foxtron',
    'Geely',
    'Genesis',
    'GMC',
    'Great Wall',
    'Haval',
    'Honda',
    'Hummer',
    'Hyundai',
    'Ineos',
    'Infiniti',
    'Iran Khodro',
    'JAC',
    'Jaguar',
    'Jeep',
    'JETOUR',
    'KIA',
    'Koenigsegg',
    'Lada',
    'Lamborghini',
    'Lancia',
    'Land Rover',
    'Lexus',
    'Lifan',
    'Lincoln',
    'Lordstown',
    'Lotus',
    'Lucid',
    'LvChi',
    'Maserati',
    'Maybach',
    'Mazda',
    'MCLaren',
    'Mercedes-Benz',
    'MG',
    'MINI',
    'Mitsubishi',
    'Nikola',
    'NIO',
    'Nissan',
    'Opel',
    'Pagani',
    'Peugeot',
    'Polestar',
    'Porsche',
    'Qoros',
    'Range Rover',
    'Ravon',
    'Renault',
    'Rimac',
    'Rivian',
    'Rolls-Royce',
    'Saab',
    'Saipa',
    'SEAT',
    'Skoda',
    'Smart',
    'Stellantis',
    'Subaru',
    'Suzuki',
    'Tata',
    'Tesla',
    'Torsus',
    'Toyota',
    'VinFast',
    'Volkswagen',
    'Volvo',
    'Xpeng',
    'Zotye',
];
